
language: node_js 
node_js:
  - 12 
services:
  - docker 


#Pre-testing install 
install: 
  - echo "nothing needs to be installed"


#Scripts to be run such as tests 
before_script:
  - echo "no tests"


script:
  - docker --version  # prints theversion for loggin 
  - docker build -t weatherlens-reverse-proxy . 
  - docker tag weatherlens-reverse-proxy fansua/weatherlens-reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fansua/weatherlens-reverse-proxy